package models;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 03:40:13 PM IST 
//




import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link STEPProductInformation }
     * 
     */
    public STEPProductInformation createSTEPProductInformation() {
        return new STEPProductInformation();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList }
     * 
     */
    public STEPProductInformation.AttributeList createSTEPProductInformationAttributeList() {
        return new STEPProductInformation.AttributeList();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute createSTEPProductInformationAttributeListAttribute() {
        return new STEPProductInformation.AttributeList.Attribute();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.Validation }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.Validation createSTEPProductInformationAttributeListAttributeValidation() {
        return new STEPProductInformation.AttributeList.Attribute.Validation();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.AttributeGroupLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.AttributeGroupLink createSTEPProductInformationAttributeListAttributeAttributeGroupLink() {
        return new STEPProductInformation.AttributeList.Attribute.AttributeGroupLink();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.UserTypeLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.UserTypeLink createSTEPProductInformationAttributeListAttributeUserTypeLink() {
        return new STEPProductInformation.AttributeList.Attribute.UserTypeLink();
    }

}
