package models;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 03:40:13 PM IST 
//




import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttributeList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Attribute" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Validation">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="BaseType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="MinValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="MaxValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="InputMask" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="AttributeGroupLink" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="AttributeGroupID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="UserTypeLink">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MultiValued" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ProductMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="FullTextIndexed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ExternallyMaintained" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Selected" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Referenced" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ExportTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExportContext" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ContextID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WorkspaceID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="UseContextLocale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SingleUpdateMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeList"
})
@XmlRootElement(name = "STEP-ProductInformation")
public class STEPProductInformation {

    @XmlElement(name = "AttributeList", required = true)
    protected STEPProductInformation.AttributeList attributeList;
    @XmlAttribute(name = "ExportTime")
    protected String exportTime;
    @XmlAttribute(name = "ExportContext")
    protected String exportContext;
    @XmlAttribute(name = "ContextID")
    protected String contextID;
    @XmlAttribute(name = "WorkspaceID")
    protected String workspaceID;
    @XmlAttribute(name = "UseContextLocale")
    protected String useContextLocale;
    @XmlAttribute(name = "SingleUpdateMode")
    protected String singleUpdateMode;

    /**
     * Gets the value of the attributeList property.
     * 
     * @return
     *     possible object is
     *     {@link STEPProductInformation.AttributeList }
     *     
     */
    public STEPProductInformation.AttributeList getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link STEPProductInformation.AttributeList }
     *     
     */
    public void setAttributeList(STEPProductInformation.AttributeList value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the exportTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportTime() {
        return exportTime;
    }

    /**
     * Sets the value of the exportTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportTime(String value) {
        this.exportTime = value;
    }

    /**
     * Gets the value of the exportContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportContext() {
        return exportContext;
    }

    /**
     * Sets the value of the exportContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportContext(String value) {
        this.exportContext = value;
    }

    /**
     * Gets the value of the contextID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextID() {
        return contextID;
    }

    /**
     * Sets the value of the contextID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextID(String value) {
        this.contextID = value;
    }

    /**
     * Gets the value of the workspaceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkspaceID() {
        return workspaceID;
    }

    /**
     * Sets the value of the workspaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkspaceID(String value) {
        this.workspaceID = value;
    }

    /**
     * Gets the value of the useContextLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseContextLocale() {
        return useContextLocale;
    }

    /**
     * Sets the value of the useContextLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseContextLocale(String value) {
        this.useContextLocale = value;
    }

    /**
     * Gets the value of the singleUpdateMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSingleUpdateMode() {
        return singleUpdateMode;
    }

    /**
     * Sets the value of the singleUpdateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSingleUpdateMode(String value) {
        this.singleUpdateMode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Attribute" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Validation">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="BaseType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MinValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MaxValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="InputMask" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="AttributeGroupLink" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="AttributeGroupID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="UserTypeLink">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="MultiValued" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ProductMode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="FullTextIndexed" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ExternallyMaintained" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Selected" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Referenced" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attribute"
    })
    public static class AttributeList {

        @XmlElement(name = "Attribute")
		public List<STEPProductInformation.AttributeList.Attribute> attribute;

        /**
         * Gets the value of the attribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttribute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link STEPProductInformation.AttributeList.Attribute }
         * 
         * 
         */
        public List<STEPProductInformation.AttributeList.Attribute> getAttribute() {
            if (attribute == null) {
                attribute = new ArrayList<STEPProductInformation.AttributeList.Attribute>();
            }
            return this.attribute;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Validation">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="BaseType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MinValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MaxValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="InputMask" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="AttributeGroupLink" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="AttributeGroupID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="UserTypeLink">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="MultiValued" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ProductMode" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="FullTextIndexed" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ExternallyMaintained" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Derived" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Selected" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Referenced" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Mandatory" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "validation",
            "attributeGroupLink",
            "userTypeLink"
        })
        public static class Attribute {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Validation", required = true)
            protected STEPProductInformation.AttributeList.Attribute.Validation validation;
            @XmlElement(name = "AttributeGroupLink")
            protected List<STEPProductInformation.AttributeList.Attribute.AttributeGroupLink> attributeGroupLink;
            @XmlElement(name = "UserTypeLink", required = true)
            protected List<STEPProductInformation.AttributeList.Attribute.UserTypeLink> userTypeLink;
            @XmlAttribute(name = "ID")
            protected String id;
            @XmlAttribute(name = "MultiValued")
            protected String multiValued;
            @XmlAttribute(name = "ProductMode")
            protected String productMode;
            @XmlAttribute(name = "FullTextIndexed")
            protected String fullTextIndexed;
            @XmlAttribute(name = "ExternallyMaintained")
            protected String externallyMaintained;
            @XmlAttribute(name = "Derived")
            protected String derived;
            @XmlAttribute(name = "Selected")
            protected String selected;
            @XmlAttribute(name = "Referenced")
            protected String referenced;
            @XmlAttribute(name = "Mandatory")
            protected String mandatory;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the validation property.
             * 
             * @return
             *     possible object is
             *     {@link STEPProductInformation.AttributeList.Attribute.Validation }
             *     
             */
            public STEPProductInformation.AttributeList.Attribute.Validation getValidation() {
                return validation;
            }

            /**
             * Sets the value of the validation property.
             * 
             * @param value
             *     allowed object is
             *     {@link STEPProductInformation.AttributeList.Attribute.Validation }
             *     
             */
            public void setValidation(STEPProductInformation.AttributeList.Attribute.Validation value) {
                this.validation = value;
            }

            /**
             * Gets the value of the attributeGroupLink property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeGroupLink property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeGroupLink().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link STEPProductInformation.AttributeList.Attribute.AttributeGroupLink }
             * 
             * 
             */
            public List<STEPProductInformation.AttributeList.Attribute.AttributeGroupLink> getAttributeGroupLink() {
                if (attributeGroupLink == null) {
                    attributeGroupLink = new ArrayList<STEPProductInformation.AttributeList.Attribute.AttributeGroupLink>();
                }
                return this.attributeGroupLink;
            }

            /**
             * Gets the value of the userTypeLink property.
             * 
             * @return
             *     possible object is
             *     {@link STEPProductInformation.AttributeList.Attribute.UserTypeLink }
             *     
             */
            public List<STEPProductInformation.AttributeList.Attribute.UserTypeLink> getUserTypeLink() {
            	if (userTypeLink == null) {
            		userTypeLink = new ArrayList<STEPProductInformation.AttributeList.Attribute.UserTypeLink>();
                }
                return this.userTypeLink;
            }

            /**
             * Sets the value of the userTypeLink property.
             * 
             * @param value
             *     allowed object is
             *     {@link STEPProductInformation.AttributeList.Attribute.UserTypeLink }
             *     
             */
            public void setUserTypeLink(List<STEPProductInformation.AttributeList.Attribute.UserTypeLink> value) {
                this.userTypeLink = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the multiValued property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMultiValued() {
                return multiValued;
            }

            /**
             * Sets the value of the multiValued property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMultiValued(String value) {
                this.multiValued = value;
            }

            /**
             * Gets the value of the productMode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductMode() {
                return productMode;
            }

            /**
             * Sets the value of the productMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductMode(String value) {
                this.productMode = value;
            }

            /**
             * Gets the value of the fullTextIndexed property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullTextIndexed() {
                return fullTextIndexed;
            }

            /**
             * Sets the value of the fullTextIndexed property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullTextIndexed(String value) {
                this.fullTextIndexed = value;
            }

            /**
             * Gets the value of the externallyMaintained property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExternallyMaintained() {
                return externallyMaintained;
            }

            /**
             * Sets the value of the externallyMaintained property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExternallyMaintained(String value) {
                this.externallyMaintained = value;
            }

            /**
             * Gets the value of the derived property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDerived() {
                return derived;
            }

            /**
             * Sets the value of the derived property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDerived(String value) {
                this.derived = value;
            }

            /**
             * Gets the value of the selected property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSelected() {
                return selected;
            }

            /**
             * Sets the value of the selected property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSelected(String value) {
                this.selected = value;
            }

            /**
             * Gets the value of the referenced property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferenced() {
                return referenced;
            }

            /**
             * Sets the value of the referenced property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferenced(String value) {
                this.referenced = value;
            }

            /**
             * Gets the value of the mandatory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMandatory() {
                return mandatory;
            }

            /**
             * Sets the value of the mandatory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMandatory(String value) {
                this.mandatory = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="AttributeGroupID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class AttributeGroupLink {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "AttributeGroupID")
                protected String attributeGroupID;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the attributeGroupID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAttributeGroupID() {
                    return attributeGroupID;
                }

                /**
                 * Sets the value of the attributeGroupID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAttributeGroupID(String value) {
                    this.attributeGroupID = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="UserTypeID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class UserTypeLink {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "UserTypeID")
                protected String userTypeID;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the userTypeID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUserTypeID() {
                    return userTypeID;
                }

                /**
                 * Sets the value of the userTypeID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUserTypeID(String value) {
                    this.userTypeID = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="BaseType" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MinValue" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MaxValue" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="InputMask" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Validation {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "BaseType")
                protected String baseType;
                @XmlAttribute(name = "MinValue")
                protected String minValue;
                @XmlAttribute(name = "MaxValue")
                protected String maxValue;
                @XmlAttribute(name = "MaxLength")
                protected String maxLength;
                @XmlAttribute(name = "InputMask")
                protected String inputMask;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the baseType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBaseType() {
                    return baseType;
                }

                /**
                 * Sets the value of the baseType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBaseType(String value) {
                    this.baseType = value;
                }

                /**
                 * Gets the value of the minValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinValue() {
                    return minValue;
                }

                /**
                 * Sets the value of the minValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinValue(String value) {
                    this.minValue = value;
                }

                /**
                 * Gets the value of the maxValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaxValue() {
                    return maxValue;
                }

                /**
                 * Sets the value of the maxValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaxValue(String value) {
                    this.maxValue = value;
                }

                /**
                 * Gets the value of the maxLength property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaxLength() {
                    return maxLength;
                }

                /**
                 * Sets the value of the maxLength property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaxLength(String value) {
                    this.maxLength = value;
                }

                /**
                 * Gets the value of the inputMask property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInputMask() {
                    return inputMask;
                }

                /**
                 * Sets the value of the inputMask property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInputMask(String value) {
                    this.inputMask = value;
                }

            }

        }

    }

}
